version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080

functions:
  main-node:
    lang: node22
    handler: ./functions/main-node
    image: localhost:5000/main-node:latest
    environment:
      write_debug: true
    annotations:
      com.openfaas.scale.zero: "true"
  uppercase-python:
    lang: python3-http
    handler: ./functions/uppercase-python
    image: localhost:5000/uppercase-python:latest
    environment:
      write_debug: true
    annotations:
      com.openfaas.scale.zero: "true"
  reverse-node:
    lang: node22
    handler: ./functions/reverse-node
    image: localhost:5000/reverse-node:latest
    environment:
      write_debug: true
    annotations:
      com.openfaas.scale.zero: "true"


